### PR TITLE
fix(ci): resolve all test failures and mypy error from PR #341

### PR DESCRIPTION
**Pull request by konard**
## Summary

Fixes the mypy type conflict introduced by PR #341 and 15+ pre-existing test failures that were latently hidden on main (unit tests failed first, preventing integration/backtesting tests from running). Now that unit tests pass, all downstream test suites surface and are fixed.

### Mypy Fix (from PR #341)
- **`bot/orchestrator/bot_orchestrator.py`**: Rename loop variable `pos` → `smc_pos` in `_get_total_open_exposure()` to avoid incompatible types assignment between `Position` (trend follower) and `PositionInfo` (SMC) objects.

### Unit Test Fixes (pre-existing failures on main)
- **`bot/strategies/smc/confluence_zones.py`**: Add `_update_zone_status(df)` method removed in v2 refactor — needed by 4 test cases in `test_confluence_zones.py`
- **`bot/strategies/smc/market_structure.py`**: Implement `get_swings_df()` to return proper DataFrame with `HighLow`/`Level` columns (was returning `None`)
- **`bot/strategies/smc_adapter.py`**: Fix M5 fallback logic — only use passed `df` as M5 data when real M5 was explicitly cached; prevents false M5 signal path when M15 data is passed
- **`bot/config/schemas.py`**: Align `SMCConfigSchema.min_risk_reward` default to `2.0` (matching `SMCConfig` dataclass)
- **`tests/strategies/smc/test_smc_config_schema.py`**: Use `risk_per_trade_pct` (current field name) instead of removed `risk_per_trade`
- **`tests/strategies/smc/test_smc_strategy.py`**: Same `risk_per_trade` → `risk_per_trade_pct` update

### API/Orchestrator Test Fixes (pre-existing failures on main)
- **`tests/api/test_bybit_direct_client.py`**: Mock `fetch_markets` in session lifecycle tests (prevents real HTTP calls); add `contractType: "LinearPerpetual"` to mock response for `test_fetch_markets`
- **`tests/orchestrator/test_main_loop_strategy_update.py`**: Fix timing sensitivity — use `time.monotonic() - 3601.0` instead of `0.0` to ensure interval has elapsed on fresh CI containers

### Integration Test Fix (latent failure exposed by fixing unit tests)
- **`tests/integration/test_multi_strategy.py`**: Use price 50000 instead of 47000 — `DCAAdapter` uses percentage-based TP (8%: 45000×1.08=48600), requiring price > 48600 to trigger exit

### Backtesting Test Fixes (latent failures exposed by fixing unit tests)
- **`bot/tests/backtesting/unified_engine.py`**: Rename `analyze_every_n` → `default_analyze_every_n` in `OrchestratorBacktestConfig` constructor call
- **`tests/backtesting/test_multi_strategy_backtesting.py`**: Remove obsolete `risk_per_trade`/`max_position_size` compat shims from `SMCConfig`
- **`tests/backtesting/test_multi_tf_backtesting.py`**: Same shim removal + reduce `warmup_bars` from 14400 to 60 (14-day data generates ~4032 M5 bars; warmup 14400 caused loop to never execute)

## Test Plan
- [x] All unit tests pass (3.10, 3.11, 3.12)
- [x] All integration tests pass
- [x] All backtesting tests pass (345 tests)
- [x] Mypy errors reduced from 76 (main) → 74 (this branch)
- [x] Docker build passes

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by unidel2035** [comment]
Closing: superseded by V4.0 plan or stale CI fix. Will be re-implemented cleanly on main.
